apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: deploy-task
spec:
  params:
    - name: task-pvc
      description: the task pvc - this is the volume where the files (Dockerfile etc..) are expected to be
    - name: cluster
      description: cluster name
    - name: continuous-delivery-context-secret
      description: name of the configmap containing the continuous delivery pipeline context secrets
      default: cd-secret
  steps:
    - name: deploy-step
      image: icr.io/continuous-delivery/pipeline/pipeline-base-image:2.23
      workingDir: /artifacts
      env:
        - name: CLUSTER
          value: $(params.cluster)
        - name: API_KEY
          valueFrom:
            secretKeyRef:
              name: $(params.continuous-delivery-context-secret)
              key: API_KEY
      command: ["/bin/bash", "-c"]
      args:
        - |
          set -e -o pipefail
          
          ibmcloud login --apikey $API_KEY --no-region
          ibmcloud ks cluster config -c $CLUSTER

          kubectl apply -f helloworldapp/deployment.yaml
              
      volumeMounts:
        - mountPath: /artifacts
          name: task-volume
  volumes:
    - name: task-volume
      persistentVolumeClaim:
        claimName: $(params.task-pvc)


  