apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pipeline
spec:
  params:
    - name: pipeline-pvc
      description: the pipeline pvc name
    - name: git-repo
    - name: cluster
  tasks:
    - name: git-clone-task
      taskRef:
        name: git-clone-task
      params:
        - name: task-pvc
          value: $(params.pipeline-pvc)
        - name: git-repo
          value: $(params.git-repo)
    - name: docker-build-task
      taskRef:
        name: docker-build-task
      runAfter:
        - git-clone-task
      params:
        - name: task-pvc
          value: $(params.pipeline-pvc)
    - name: deploy-task
      taskRef:
        name: deploy-task
      runAfter:
        - docker-build-task
      params:
        - name: task-pvc
          value: $(params.pipeline-pvc)
        - name: cluster
          value: $(params.cluster)
        